title: FoodRecipes
subtitle: Some Recipes for the faint hearted people
email: someotheremail@email.com
twitter: someid

url: 
baseurl: '/'

markdown: kramdown

exclude:
- "*.gemspec"

sass:
  sass_dir: assets/bsd5
  style: compressed